name: 'Secuoyas Techdocs'
description: 'Builds and pushes techdocs to Backstage'
inputs:
  name:
    description: 'name of the component'
    required: true
  plugins:
    description: 'list of additional python plugin dependencies to add'
    required: false
  aws_role_to_assume_arn:
    description: AWS role para poder subir ficheros
    required: true
  aws_bucket:
    description: AWS bucket
    required: true
  aws_region:
    description: AWS region
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.0'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install techdocs-cli
      shell: bash
      run: sudo npm install -g @techdocs/cli

    - name: Install mkdocs and mkdocs plugins
      shell: bash
      run: |
        python -m pip install mkdocs-techdocs-core==1.*
        python -m pip install pymdown-extensions==10.0.1

    - name: Generate docs site
      shell: bash
      run: techdocs-cli generate --no-docker --verbose

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.aws_role_to_assume_arn }}
        aws-region: ${{ inputs.aws_region }}
        role-session-name: techdocs-uploader-session

    - name: Upload to S3
      shell: bash
      run: |
        ls -l
        aws s3 sync site ${{ inputs.aws_bucket }}/default/component/${{ github.event.repository.name }}
